### ISSUE TITLE
2 Issues with compressed wide BVH traversal shader

### ISSUE THREAD

**Issue by JuicyStandoffishMan** [AlerianEmperor/CaitlynRenderer#1]
Sorry that I'm not submitting this as a PR, but there are 2 issues in cwbvh.fs that need to be fixed.

1. The plane testing uses the wrong min function:
`float tmax = max(max(tmax3.x, tmax3.y), tmax3.z);`
Should be:
`float tmax = min(min(tmax3.x, tmax3.y), tmax3.z);`

2. The stack pointer needs to be decremented before it's referenced, otherwise the ray never terminates and reads garbage data:
`current_group = local_stack[stack_size--];`
Should be:
`current_group = local_stack[--stack_size];`

**Comment by AlerianEmperor** [comment]
Hi there!
Thanks for submit something, I think this project is already covered in dust for lack of public interest. 
The problem with cwbvh is I purposely make it this way. 

Yes, you hear it right. 

There are 3 reasons for this:

1. I have a perfectly working cwbvh but I posted the incomplete one, sbvh is 100% correct and reliable, no need to check. But cwbvh only work if I set the screen space really small. Some how the binding texture of opengl consume to much memory so it unnable to run on big screen mode. I will go back to this when I complete my current opengl and vulkan engine and add bindless texture.

2. currently I am working on an opengl and vulkan engine so I am not actively maintain the ray tracing projects, so you dont see any new updates.

3. Sometime I really sad to see my projects are getting no where. They were created so I can get a job in a US company
 I invest a lot of times making projects like lux renderer and caitlyn renderer, the did get contact from Amazon Luna, Meta, two step incetive. But they all ghost me afterward without any further consideration.

3 is what I upset the most, there are people who work at NVIDIA who still reading the book: "physically based rendering", which I have finished over 2 years ago, have no projects, nothing impressive and still got the jobs! wow. And I got message like: "you are not qualified" or "we are pursuing other more suitable candidate!".

It's not like I can not find a job, but I am living in a third world country which is on its way to a complete downfall. I can find high salary job in my country with ease, but there is no future in doing so. And now I am stuck jobless, lable as loser who can not find a job...

Even worse, people on github dont find my projects interesting either, the similar knightcrawler25 glsl pathtracer have like 1.7k star, why I have none for like 7 months, and caitlyn renderer have much simpler code, but people just don't care. They think my project can be a good alternative, they download and leave!

I dont want to make it like a complain post, it just I don't have much motivation to update. The road map is I will public one opengl engine, one vulkan engine, one upgrade raster engine, and if have time work on svgf. And even if all of this dont land me a job so I can continue with my others plans. I will just leave github forever!

Thank you raising your issue, I wish you all the best!

**Comment by AlerianEmperor** [comment]
And moreover, the first error is indeed typos error, the second is actually correct, stack_size have actually increase, that value have to be use first before decrease. so stack_size-- is correct. 
The fact that these kind of error do not bother me much since I have two cwbvh versions:

The first version I put here, except the first error, don't have any error but fail to run. The upside is the code is much cleaner.
The second version work fine, but only if I set screen space to small value, the code is longer and more messy.

But github users rather give like to some silly youtube videos than my code, why am I bother to fix.

**Comment by AlerianEmperor** [comment]
The first error is indeed typos error, the second is correct, stack_size have actually increase, that value have to be use first before decrease. so stack_size-- is correct.
